

# This file was *autogenerated* from the file beams_bending.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_2p = RealNumber('2.'); _sage_const_3p = RealNumber('3.'); _sage_const_6p = RealNumber('6.'); _sage_const_4p = RealNumber('4.'); _sage_const_24p = RealNumber('24.'); _sage_const_5p = RealNumber('5.'); _sage_const_120p = RealNumber('120.'); _sage_const_25p = RealNumber('25.'); _sage_const_0p = RealNumber('0.'); _sage_const_500 = Integer(500)
import os
import numpy as np


'''
# Parameters
P = 10000.
M = 5000.
Q1 = 2000.
Q2 = 5000.
K = 1.0e6
E = 2.1e11  # steel
J = 1.0e-4

# Coordinates
x_Q1 = 0.
x_Q2 = 8.
x_R1 = 6.
x_R2 = 10.
x_K = 12.
x_M = 15.
x_P = 19.
x_R3 = 22.
'''


f = open ("../../data/parameters.txt", 'r')
parameters = [float (i) for i in f.readline ().split ()]
P = parameters[_sage_const_0 ]
M = parameters[_sage_const_1 ]
Q1 = parameters[_sage_const_2 ]
Q2 = parameters[_sage_const_3 ]
K = parameters[_sage_const_4 ]
E = parameters[_sage_const_5 ]  # steel
J = parameters[_sage_const_6 ]
f.close ()

f = open ("../../data/coordinates.txt", 'r')
coordinates = [float (i) for i in f.readline ().split ()]
x_Q1 = coordinates[_sage_const_0 ]
x_Q2 = coordinates[_sage_const_1 ]
x_R1 = coordinates[_sage_const_2 ]
x_R2 = coordinates[_sage_const_3 ]
x_K = coordinates[_sage_const_4 ]
x_M = coordinates[_sage_const_5 ]
x_P = coordinates[_sage_const_6 ]
x_R3 = coordinates[_sage_const_7 ]
f.close ()

# print ("parameters = ", parameters)
# print ("coordinates = ", coordinates)


# Variables
x = var ('x')
M_0 = var ('M_0')
Q_0 = var ('Q_0')
R1 = var ('R1')
R2 = var ('R2')
R3 = var ('R3')
R_K = var ('R_K')


# The deflection equation
tan = (Q2 - Q1) / (x_Q2 - x_Q1)
W = (_sage_const_1  / (E * J)) * 	(- M_0 * (x ** _sage_const_2p ) / _sage_const_2p  	- Q_0 * (x ** _sage_const_3p ) / _sage_const_6p   	- (M * ((x - x_M) ** _sage_const_2p ) / _sage_const_2p ) * heaviside (x - x_M) 	+ (P * ((x - x_P) ** _sage_const_3p ) / _sage_const_6p ) * heaviside (x - x_P) 	- (R1 * ((x - x_R1) ** _sage_const_3p ) / _sage_const_6p ) * heaviside (x - x_R1) 	- (R2 * ((x - x_R2) ** _sage_const_3p ) / _sage_const_6p ) * heaviside (x - x_R2) 	- (R3 * ((x - x_R3) ** _sage_const_3p ) / _sage_const_6p ) * heaviside (x - x_R3) 	- (R_K * ((x - x_K) ** _sage_const_3p ) / _sage_const_6p ) * heaviside (x - x_K) 	+ (Q1 * ((x - x_Q1) ** _sage_const_4p ) / _sage_const_24p  + tan * ((x - x_Q1) ** _sage_const_5p ) / _sage_const_120p ) * heaviside (x - x_Q1) 	- (Q2 * ((x - x_Q2) ** _sage_const_4p ) / _sage_const_24p  + tan * ((x - x_Q2) ** _sage_const_5p ) / _sage_const_120p ) * heaviside (x - x_Q2))

# print ("W = ", W, '\n')
# print (diff (W, x))

__tmp__=var("x"); zero = symbolic_expression(_sage_const_0 ).function(x)
Theta = diff (W, x).substitute_function (dirac_delta, zero)
Moment = diff (Theta, x).substitute_function (dirac_delta, zero)
Q = diff (Moment, x).substitute_function (dirac_delta, zero)

# print ("Moment = ", Moment, '\n')
# print ("Q = ", Q, '\n')

sol = solve ([
	Moment (x = _sage_const_25p ) == _sage_const_0p , Q (x = _sage_const_25p ) == _sage_const_0p ,
	W (x = x_R1) == _sage_const_0p , W (x = x_R2) == _sage_const_0p , W (x = x_R3) == _sage_const_0p ,
	W (x = x_K) * K == - R_K],
	R1, R2, R3, R_K, Q_0, M_0, solution_dict = True)

# print (sol)
# print (sol[0])
# print (type (sol[0][R1].substitute_function (heaviside, zero)))
# print (sol[0][R1])
# print (sol[0][R1].substitute_function (heaviside, zero))
# R1 = float (sol[0][R1].substitute_function (heaviside, zero))

R1 = float (sol[_sage_const_0 ][R1])
R2 = float (sol[_sage_const_0 ][R2])
R3 = float (sol[_sage_const_0 ][R3])
R_K = float (sol[_sage_const_0 ][R_K])
Q_0 = float (sol[_sage_const_0 ][Q_0])
M_0 = float (sol[_sage_const_0 ][M_0])

# print ("R1 = ", R1)
# print ("R2 = ", R2)
# print ("R3 = ", R3)
# print ("W = ", W)

__tmp__=var("x"); s_W = symbolic_expression(W (R1 = R1, R2 = R2, R3 = R3, R_K = R_K, Q_0 = Q_0, M_0 = M_0)).function(x)
__tmp__=var("x"); s_Theta = symbolic_expression(Theta (R1 = R1, R2 = R2, R3 = R3, R_K = R_K, Q_0 = Q_0, M_0 = M_0)).function(x)
__tmp__=var("x"); s_Moment = symbolic_expression(Moment (R1 = R1, R2 = R2, R3 = R3, R_K = R_K, Q_0 = Q_0, M_0 = M_0)).function(x)
__tmp__=var("x"); s_Q = symbolic_expression(Q (R1 = R1, R2 = R2, R3 = R3, R_K = R_K, Q_0 = Q_0, M_0 = M_0)).function(x)

# print ("s_W = ", s_W, '\n')
# print ("s_Theta = ", s_Theta, '\n')
# print ("s_Moment = ", s_Moment, '\n')
# print ("s_Q = ", s_Q, '\n')

# print ("s_W (x = 1) = ", s_W (x = 1), '\n')

grid = np.linspace (_sage_const_0p , _sage_const_25p , _sage_const_500 )

# print (s_Moment (x = grid[5]))
# print (s_Moment (x = grid[5]).substitute_function (heaviside, zero))
# s_W_grid = [s_W (x = x_grid) for x_grid in grid]

s_W_grid = [s_W (x = x_grid) for x_grid in grid]
s_Theta_grid = [s_Theta (x = x_grid) for x_grid in grid]
s_Moment_grid = [s_Moment (x = x_grid) for x_grid in grid]
s_Q_grid = [s_Q (x = x_grid) for x_grid in grid]

# print (s_W_grid)



# Export results

file = open ("../../results/sage_res_x.txt", 'w')
for i in range (len (grid)):
    file.write (str (grid[i]))
    file.write (' ')
file.close ()

file = open ("../../results/sage_res_W.txt", 'w')
for i in range (len (grid)):
    file.write (str (s_W_grid[i]))
    file.write (' ')
file.close ()

file = open ("../../results/sage_res_Theta.txt", 'w')
for i in range (len (grid)):
    file.write (str (s_Theta_grid[i]))
    file.write (' ')
file.close ()

file = open ("../../results/sage_res_Moment.txt", 'w')
for i in range (len (grid)):
    file.write (str (s_Moment_grid[i]))
    file.write (' ')
file.close ()

file = open ("../../results/sage_res_Q.txt", 'w')
for i in range (len (grid)):
    file.write (str (s_Q_grid[i]))
    file.write (' ')
file.close ()

